# Generated by Django 3.1.1 on 2020-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField()),
                ('descricao', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
    ]
